runtime: nodejs18
instance_class: F2
env_variables:
  BUCKET_NAME: "calcwt"
handlers:
  - url: /
    static_files: dist/shoppinglist/index.html
    upload: dist/shoppinglist/index.html 
  - url: /
    static_dir: dist/shoppinglist